import os

COL_COUNT = 20
ROW_COUNT = 10
SPRITE_SIZE = 48
REFRESH_RATE = 1

RESOURCES_DIR = '/content/VoiceCOntrolledGame/pilichm/data/'
# RESOURCES_DIR = f'{os.path.dirname(os.path.abspath(__file__))}/pilichm/data/'

SPRITE_PLAYER_UNARMED_RIGHT_FILE = f'{RESOURCES_DIR}hero_right.png'
SPRITE_PLAYER_UNARMED_LEFT_FILE = f'{RESOURCES_DIR}hero_left.png'
SPRITE_PLAYER_UNARMED_UP_FILE = f'{RESOURCES_DIR}hero_up.png'
SPRITE_PLAYER_UNARMED_DONW_FILE = f'{RESOURCES_DIR}hero_dawn.png'

SPRITE_PLAYER_ARMED_RIGHT_FILE = f'{RESOURCES_DIR}hero_armed_right.png'
SPRITE_PLAYER_ARMED_LEFT_FILE = f'{RESOURCES_DIR}hero_armed_left.png'
SPRITE_PLAYER_ARMED_UP_FILE = f'{RESOURCES_DIR}hero_armed_up.png'
SPRITE_PLAYER_ARMED_DOWN_FILE = f'{RESOURCES_DIR}hero_armed_down.png'

MAIN_BACKGROUND_FILE = f'{RESOURCES_DIR}main_screen.png'

SPRITE_GRASS_FILE = f'{RESOURCES_DIR}grass_1.png'
SPRITE_WATER_FILE = f'{RESOURCES_DIR}water_1.png'
SPRITE_BRIDGE_FILE = f'{RESOURCES_DIR}bridge_1.png'
SPRITE_HEART_EQUIPPED_FILE = f'{RESOURCES_DIR}heart_1.png'
SPRITE_HEART_BONUS_FILE = f'{RESOURCES_DIR}heart_bonus_1.png'
SPRITE_SWORD_EQUIPPED_FILE = f'{RESOURCES_DIR}sword_equipped.png'
SPRITE_SWORD_BONUS_FILE = f'{RESOURCES_DIR}sword_bonus.png'
SPRITE_SCREEN_BORDER_FILE = f'{RESOURCES_DIR}screen_border_1.png'
SPRITE_STUMP_FILE = f'{RESOURCES_DIR}stump_1.png'
SPRITE_TREE_FILE = f'{RESOURCES_DIR}tree_1.png'
SPRITE_BUSH_FILE = f'{RESOURCES_DIR}bush_1.png'
SPRITE_ENEMY_1_LIFE = f'{RESOURCES_DIR}enemy_1.png'
SPRITE_ENEMY_2_LIFES = f'{RESOURCES_DIR}enemy_2.png'
SPRITE_FLAG_FILE = f'{RESOURCES_DIR}flag_1.png'
SPRITE_BOOK_FILE = f'{RESOURCES_DIR}book_1.png'

ALLOWED_TERRAIN = [SPRITE_GRASS_FILE, SPRITE_BRIDGE_FILE, SPRITE_HEART_BONUS_FILE, SPRITE_SWORD_BONUS_FILE,
                   SPRITE_BOOK_FILE]

INIT_STATE_FILE = f'{RESOURCES_DIR}game_init_state.csv'

screen_dict = {0: SPRITE_GRASS_FILE, 1: SPRITE_WATER_FILE, 3: SPRITE_BRIDGE_FILE, 4: SPRITE_STUMP_FILE,
               5: SPRITE_TREE_FILE, 6: SPRITE_BUSH_FILE, 7: SPRITE_SCREEN_BORDER_FILE, 8: SPRITE_HEART_BONUS_FILE,
               9: SPRITE_SWORD_BONUS_FILE, 10: SPRITE_ENEMY_2_LIFES, 11: SPRITE_FLAG_FILE, 12: SPRITE_BOOK_FILE}
